---
collections:
  - name: community.general
    version: 5.6.0
  - name: community.sops
    version: 1.4.0
  - name: ansible.posix
    version: 1.4.0
  - name: ansible.utils
    version: 2.6.1

roles:
  - src: geerlingguy.pip
    version: 2.2.0
  - src: geerlingguy.docker
    version: 6.0.1
  - src: https://github.com/PyratLabs/ansible-role-k3s.git
    scm: git
    name: xanmanning.k3s
    version: 80e4debcd4a7b4c8d596a380743ca1017acad43d
  - src: https://github.com/mrlesmithjr/ansible-zfs.git
    scm: git
    name: mrlesmithjr.zfs
    version: b80e84d6938eb7730faeffc7ff7d8aa06ad5bef7