# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:ob8XAqQ=,iv:h380tZ9AxHi1Cw0mW/lEPES/2ss8q8q1y8CmreWCLis=,tag:EcmwBZPTNVhFN56EO9+o3Q==,type:str]
    admin-password: ENC[AES256_GCM,data:wA1afvZNezthWpcR,iv:55SYB2swLRSGslNsQiw38h0lzeu3S3CkYGzML2/5vgk=,tag:ngQbv/pLIrJHGJD3GqHIyQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZTENNVHg1YnNMem4xYlRI
            SjVQV2RtWGVwT3VwY1F0TWJ1azBLMGVNVkJVCmZScHNvNGhnZ3RGNXk3RXo0T2NG
            T2RmYnBiei8yZUhtT0ZEWDRaMEl1NlkKLS0tIGJDbWdQNHVEMG41cDRrd2JjK1kz
            YXFzbEJuYS9JVDU4MU9TV1lXMWFlS00KnJZw6LK9VVIZfvsXCfxJOEfuBCjzq0s6
            ARzQIyrHxj5oudqWOYwiMtwRywjnFmMPGiyOM9M7D9UABDmTpURz9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-02T14:54:42Z"
    mac: ENC[AES256_GCM,data:zCs1a6HjCslgOIKf3jBmvcCu02h8Y4uLyZZum/9Kr2u6UNSjkIuz63o6DzJYVsBVrMxiwa5qMs43C55SiGrbAvUoxc/lWAncOOul93Im0xh9XN1OOyt2Aged6sOlh99/9tQYnjfddR6GK9ut8EnlKeCFz68aO3dCJkCrpS+1WvE=,iv:BhmxEaCMDz8FdxAmRRPzdsRYHXFG45dBpPh5CQGBTt0=,tag:pB8IurS7IBqoDznOqBxyjw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: grafana
    namespace: monitoring
stringData:
    GF_DATABASE_USER: ENC[AES256_GCM,data:2JqciDoxCA==,iv:PKSEHPtkoclzpQQE/HGe6f0B0IEtLA5GsGbj65M7jbY=,tag:faZU++FXyu9+ioTN2/ifmA==,type:str]
    GF_DATABASE_PASSWORD: ENC[AES256_GCM,data:0gjnwbrLulIGF1vl,iv:NFRPnK1tomrErZhGUVdBQJXpeT9XNcvLN02SDZwy58o=,tag:8cF/QaXCQWnufmHsiQ4d2Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZTENNVHg1YnNMem4xYlRI
            SjVQV2RtWGVwT3VwY1F0TWJ1azBLMGVNVkJVCmZScHNvNGhnZ3RGNXk3RXo0T2NG
            T2RmYnBiei8yZUhtT0ZEWDRaMEl1NlkKLS0tIGJDbWdQNHVEMG41cDRrd2JjK1kz
            YXFzbEJuYS9JVDU4MU9TV1lXMWFlS00KnJZw6LK9VVIZfvsXCfxJOEfuBCjzq0s6
            ARzQIyrHxj5oudqWOYwiMtwRywjnFmMPGiyOM9M7D9UABDmTpURz9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-02T14:54:42Z"
    mac: ENC[AES256_GCM,data:zCs1a6HjCslgOIKf3jBmvcCu02h8Y4uLyZZum/9Kr2u6UNSjkIuz63o6DzJYVsBVrMxiwa5qMs43C55SiGrbAvUoxc/lWAncOOul93Im0xh9XN1OOyt2Aged6sOlh99/9tQYnjfddR6GK9ut8EnlKeCFz68aO3dCJkCrpS+1WvE=,iv:BhmxEaCMDz8FdxAmRRPzdsRYHXFG45dBpPh5CQGBTt0=,tag:pB8IurS7IBqoDznOqBxyjw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres_superuser
    namespace: monitoring
stringData:
    PG_SUPERUSER_USER: ENC[AES256_GCM,data:+JK+3Q==,iv:O4tPSOZWbxUZ7bm163gv5MLlzXAykPr1364Oe9r3ldQ=,tag:OixsrVNkyafrgdOhcZqQRA==,type:str]
    PG_SUPERUSER_PWD: ENC[AES256_GCM,data:mq6PVG+YkXS12lYA,iv:Co1mXCe/vJoJT1zOADadOvr9uROVJQ+smj0nzQ5ZGQY=,tag:NhmgwmLWkdBykuYNrUJAmg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZTENNVHg1YnNMem4xYlRI
            SjVQV2RtWGVwT3VwY1F0TWJ1azBLMGVNVkJVCmZScHNvNGhnZ3RGNXk3RXo0T2NG
            T2RmYnBiei8yZUhtT0ZEWDRaMEl1NlkKLS0tIGJDbWdQNHVEMG41cDRrd2JjK1kz
            YXFzbEJuYS9JVDU4MU9TV1lXMWFlS00KnJZw6LK9VVIZfvsXCfxJOEfuBCjzq0s6
            ARzQIyrHxj5oudqWOYwiMtwRywjnFmMPGiyOM9M7D9UABDmTpURz9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-02T14:54:42Z"
    mac: ENC[AES256_GCM,data:zCs1a6HjCslgOIKf3jBmvcCu02h8Y4uLyZZum/9Kr2u6UNSjkIuz63o6DzJYVsBVrMxiwa5qMs43C55SiGrbAvUoxc/lWAncOOul93Im0xh9XN1OOyt2Aged6sOlh99/9tQYnjfddR6GK9ut8EnlKeCFz68aO3dCJkCrpS+1WvE=,iv:BhmxEaCMDz8FdxAmRRPzdsRYHXFG45dBpPh5CQGBTt0=,tag:pB8IurS7IBqoDznOqBxyjw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
