---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - cloudflare-ddns
  - external-dns
  - k8s-gateway
  # - metallb
  - ingress-nginx
  - tigera-operator
