---
# yaml-language-server: $schema=https://kubernetes-schemas.falhalla.com/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: redis-operator
  namespace: flux-system
spec:
  interval: 2h
  url: https://spotahome.github.io/redis-operator
