---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - cert-manager
  #- csi-driver-nfs
  - kube-vip
  #- kured
  - metrics-server
  - reflector
  - reloader
