---
kubernetes:
  children:
    master:
      hosts:
        server1.lab:
          ansible_host: 172.16.70.15
        server2.lab:
          ansible_host: 172.16.70.16
        server3.lab:
          ansible_host: 172.16.70.17
    worker:
      hosts:
        server1.lab:
          ansible_host: 172.16.70.15
          rook_devices:
            - /dev/fedora_fedora/ceph
            - /dev/sda/
        server2.lab:
          ansible_host: 172.16.70.16
          rook_devices:
            - /dev/fedora_fedora/ceph
            - /dev/sda/
        server3.lab:
          ansible_host: 172.16.70.17
          rook_devices:
            - /dev/fedora_fedora/ceph
            - /dev/sda/
