---
kubernetes:
  children:
    master:
      hosts:
        server1:
          ansible_host: 172.16.70.10
    worker:
      hosts:
        server2:
          ansible_host: 172.16.70.20
        server3:
          ansible_host: 172.16.70.30
