---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: America/Chicago
  METALLB_LB_RANGE: 172.16.70.210-172.16.70.220
  METALLB_K8S_GATEWAY_ADDR: 172.16.70.210
  METALLB_INGRESS_ADDR: 172.16.70.211
  SVC_QBITTORRENT_ADDR: 172.16.70.212
  SVC_SMTP_RELAY_ADDR: 172.16.70.213
  SVC_PLEX_ADDR: 172.16.70.214
  METALLB_INGRESS_VPN: 172.16.70.220
  