---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: America/Chicago
  # METALLB_LB_RANGE: 172.16.70.210-172.16.70.220
  # METALLB_K8S_GATEWAY_ADDR: 172.16.70.210
  # METALLB_INGRESS_ADDR: 172.16.70.211
  SVC_QBITTORRENT_ADDR: 172.16.70.212
  SVC_SMTP_RELAY_ADDR: 172.16.70.213
  SVC_PLEX_ADDR: 172.16.70.214
  METALLB_INGRESS_VPN: 172.16.70.220

  NET_NODE_CIDR: "172.16.70.0/24"
  NET_POD_CIDR: "10.42.0.0/16"
  NET_SVC_CIDR: "10.43.0.0/16"
  NET_EIP_CIDR: "192.168.69.0/24"
  #
  SVC_EMQX_ADDR: "192.168.69.110"
  SVC_HOME_ASSISTANT_ADDR: "192.168.69.103"
  SVC_PLEX_ADDR: "192.168.69.104"
  SVC_JELLYFIN_ADDR: "192.168.69.105"
  SVC_QBITTORRENT_ADDR: "192.168.69.106"
  SVC_SYSLOG_ADDR: "192.168.69.111"
  SVC_NGINX_ADDR: "192.168.69.101"
  SVC_EMBY_ADDR: "192.168.69.107"
  SVC_SMTP_RELAY_ADDR: "192.168.69.102"
