# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:P4oH,iv:Bx0XzQOlnGGG5USJTzVPSzRcDm3Zi9AhHiahr0fMQDU=,tag:wTYU77O/EkNy00eg9SjyFw==,type:str]
    SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:7H9eIvBnb342Gu0u,iv:jZzKgkOdjmInISgwKCmuF1g9h5MNDrldxFR2Z8pB0i4=,tag:SI9Ko7Yx4mKuT0Qzz2Fdtw==,type:str]
    SECRET_PRIVATE_DOMAIN: ENC[AES256_GCM,data:6DYx,iv:YxI3SdD+yFdBV62Pko1ie4/TIWfscFfuCiT3MNzKZCs=,tag:UugPy5yABtuEjHGAfvDC/g==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:zVh3hspr0IbyczcTbUF1oGSl8Q==,iv:ccdmadifUChi01mM54JdEF+S1W3eP3CiMPHqXd+2VHo=,tag:DIU9HGJCUjrqsudlmygtaQ==,type:str]
    SECRET_EMAIL_DOMAIN: ENC[AES256_GCM,data:19D5Tp4M/ocz,iv:pBQXYIYHJ909d78mcZqRII+wS4wXFYuKlETcHwmi+jc=,tag:bLMpmIU3u/3tl95qj0upjw==,type:str]
    SECRET_AUTH_EMAIL: ENC[AES256_GCM,data:YHhH2HKsHkn1aBm0oVgOiPoLUIDf/RwrntnAvSDt3Xhm6Kacb+BWDztNMok6GTlaT3/NhPnIj8bSGPRhEHA=,iv:33WMUFb7vrbNbVYPlmWL95ZCREQGZVPLmFADIubYP4E=,tag:L30QuW/9djkuKuGTDDjQAQ==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:b+nJTZBd+1ltLQajv6cLv/WzCtKNBw==,iv:7B1hmsOdTMzN4oQZw/0fqiiHqusCSfMk5fvq5JUSct0=,tag:YnQRu8z08L2AokY/dIJU3w==,type:str]
    SECRET_PRIVATE_EMAIL: ENC[AES256_GCM,data:5MK4ArscVau/ROCrugb7dMa2xvRsew==,iv:utB3DF/DfSYMElttO0V5g/4i7zwDTIMnFo4lJlCgco0=,tag:WMeaB8cx5hBcI1ryqxeeYA==,type:str]
    SECRET_MINIO_ACCESS_KEY: null
    SECRET_MINIO_SECRET_KEY: null
    SECRET_MQTT_PASSWORD: ENC[AES256_GCM,data:ma4aQ8BVHzHRQ//n,iv:gnzTjpT7WlPNslylnUtETjhBv3YUOgQkjKCNM0By6rA=,tag:p5Z1XO36E0YJSG3uNGijhA==,type:str]
    SECRET_MQTT_USERNAME: ENC[AES256_GCM,data:CaXQJctJ,iv:u2IcdPRR6QGAP70LCIg7usHFbMJgxoo99rvNqNRPOxQ=,tag:yTvxQJIQ7k3RvjqVJmuaqg==,type:str]
    SECRET_NEXUS_USERNAME: null
    SECRET_NEXUS_PASSWORD: null
    SECRET_PIKVM_USERNAME: null
    SECRET_PIKVM_PASSWORD: null
    SECRET_UPTIMEROBOT_API_KEY: null
    SECRET_PUSHOVER_USERKEY: ENC[AES256_GCM,data:hU3kwcjSDpBW88O+mfah+8mUx6buUjd14ZfLvE+y,iv:M5Mn8GrWijlI8VEIRSrkw8OKKLNqhOu1egQ4Yp04F3I=,tag:jffq3XAGNfxBJibDhhyrvA==,type:str]
    SECRET_PUSHOVER_ALERT_MANAGER_APIKEY: ENC[AES256_GCM,data:YXnXCb7R1ktaA1LKvRpQDeflqzQgaIDgXHViC888,iv:9Xeedomxy0zU5vZ8ycfRnJnGz76tj7VlevMQz+CEUvk=,tag:aUbQLg5ijCoM5LdmP8cfPA==,type:str]
    SECRET_GITEA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:i125Bux+iTR10FlCFYtC0tO6qFqnOkuiy6OCuIMQ,iv:YBPX4ZJOcx9Vi/2og+8ao1AxiWYOY7w6x35hKxg+uFQ=,tag:ML91byROtWwFf7QJzvnygw==,type:str]
    SECRET_GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:pdkBu28FejtgfBU26Cz9H+REsgrNAxb5bZOoEcQb,iv:GJhH8JoI8nY0X2tyxhEYXxpkkXq71KnYTHlL57lm9Kw=,tag:0okT9lEbJBN5ysgE6zJDqw==,type:str]
    SECRET_MINIFLUX_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:u/SsXBwQihLmMBha1rC2oJIZZcrIOXG36KdaS9DM,iv:/NM8HTnJulwoiFp2agrZFu04yZUB27B1gNTWfFqZqd0=,tag:BXa4u68Gv1NTC2aQ8u0Z2A==,type:str]
    SECRET_MINIO_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:VMwL1E3CsLPhMy5Ff/h7IFMidReO19IWZiHWuBHv,iv:vBFRs9UsfHfqoDXQjKWUNhyF+jrAczD0Dw4ejcIFzV8=,tag:6enz+p7kRaLNn9M/3vNPgg==,type:str]
    SECRET_OUTLINE_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:IwMEDMI+B2xEpXrxqM+ufYchDscEP5tkvbnLjcdy,iv:L77pyNMopm6zfNttR+vdp5oznsr5JM4HpOWGmyp0yFQ=,tag:KjGsvVn5vo2ozPNQZ08R6g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19rtwpgqe4m68lm9e2m4r8l78uerxwfqd7z20nrx2rcjuv5lafd9qynj467
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTLzltTlY2aVFkR2dxdUdR
            UHRNeWRpT2xxdmo1QkVvUG0rcHhWQzIwZVE0CjAwWnlVbFU4TVhQOXBzS2F0SVV6
            WXNMV3NaaEFJQ0ZBR0hYeDNXcTVEUlEKLS0tIFVUdEl5OUNyTUhETzlaQzN6YzND
            dHlCL3N5djJPS0RQSUoxdEN1OXhpMVUKi+7rNMq30KP9nfj1VbwYgZF3wpiVlqE/
            YNJxlKlVnMcQuIIsK/VWouUBOgCj3nklIqNvIp4Y0FQjRQz8ZUqssg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-12T21:20:55Z"
    mac: ENC[AES256_GCM,data:fNfzwMiprE7z5A9CikSPLepmzen/dZ8kXgBS7N4SPBYlrcMtR+XsCJhknTmhaPLb5kkJ+KoNNOzjQtxBHZqwlWEhkKkFaVT0esaoUT+p6Ikk/AGJHS0FYhm5I+D/vqAUCXa9RKtXeS3Y4Hv6NgwJWeg2PizhP1zboiWLoaYDzb4=,iv:D2r2KBXrl7e1YM7dYTlSyFryibaTcLO0MOyHavTVbOA=,tag:xsXJd0MMV/bW/eVb1szhIA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
