---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  #- authelia
  - descheduler
  - excalidraw
  - lidarr
  - namespace.yaml
  - overseerr
  - prowlarr
  - qbittorrent
  - qbitorrent-jobs
  - readarr
  - recyclarr
  - sonarr
  - unpackerr
  - echo-server
  - glauth
  - hajimari
  - postgres
  - redis
