---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authelia
  - descheduler
  - excalidraw
  - intel-gpu-plugin
  - intel-gpu-exporter
  - lidarr
  - namespace.yaml
  - node-feature-discovery
  - overseerr
  - prowlarr
  - qbittorrent
  - qbittorrent-jobs
  - readarr
  - recyclarr
  - sonarr
  - unpackerr
  - echo-server
  - glauth
  #- gitea
  - hajimari
  #- minio
  - postgres
  - redis
  - theme-park
  - smtp-relay