---
# yaml-language-server: $schema=https://kubernetes-schemas.falhalla.com/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-frigate
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: cluster-apps-emqx
    - name: cluster-core-external-secrets-stores
    - name: cluster-core-rook-ceph-cluster
    - name: cluster-apps-volsync
    - name: cluster-apps-intel-device-plugin-gpu
  path: ./kubernetes/apps/default/frigate/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: frigate
      namespace: default
  interval: 30m
  retryInterval: 1m
  timeout: 3m
