---
# yaml-language-server: $schema=https://kubernetes-schemas.falhalla.com/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-snapscheduler
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: cluster-apps-snapshot-controller
  path: ./kubernetes/apps/volsync/snapscheduler/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: snapscheduler
      namespace: volsync
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
# yaml-language-server: $schema=https://kubernetes-schemas.falhalla.com/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-snapscheduler-schedules
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: cluster-apps-snapscheduler
  path: ./kubernetes/apps/volsync/snapscheduler/schedules
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
