---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - flux-system
  - kube-system
  - kube-tools
  - networking

## After Core

  - authentication
  - databases
  - development
  - documentation
  - downloaders
  - home-automation
  - media-automation
  - media-servers
  - miscellaneous
  - monitoring
  - storage
  - web-tools
