---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  #- calico-system
  - databases
  - default
  - flux-system
  - kube-system
  #- kyverno
  - monitoring
  - networking
  #- system-upgrade
