---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: sops-encrypted
  namespace: monitoring
resources:
  - helm-release.yaml
  - sumo.sops.yaml
configMapGenerator:
  - name: sumologic-map
    files:
      - values.yaml=my-values.yaml
configurations:
  - kustomizeconfig.yaml
