---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - helm-release.yaml
  - secret.sops.yaml
configMapGenerator:
  - name: my-sumologic-values
    files:
      - values.yaml=my-values.yaml
configurations:
  - kustomizeconfig.yaml
patchesStrategicMerge:
  - patches/auth.yaml
