---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - sumo.sops.yaml
configMapGenerator:
  - name: sumologicMap
    files:
      - values.yaml=my-values.yaml
configurations:
  - kustomizeconfig.yaml
