collections:
- name: ansible.posix
  version: 1.6.2
- name: community.general
  version: 12.3.0
- name: kubernetes.core
  version: 5.4.1
- name: community.sops
  version: 1.9.5
roles:
- src: geerlingguy.pip
  version: 2.2.0
- src: geerlingguy.docker
  version: 6.2.0
- name: xanmanning.k3s
  src: https://github.com/PyratLabs/ansible-role-k3s.git
  version: v3.4.1
- src: https://github.com/mrlesmithjr/ansible-zfs.git
  scm: git
  name: mrlesmithjr.zfs
  version: b80e84d6938eb7730faeffc7ff7d8aa06ad5bef7
